version: '3'
services:
  frontend:
    build: frontend
    image: frontend:latest
    # environment:
    #   PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: backend
    image: backend:latest
    # environment:
    #   PORT: 3001
    expose:
      - 3001
    ports:
      - "3001:3001"